# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package and lock
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src

# Install dependencies and build
RUN npm ci --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Set entrypoint to start the server via node
ENTRYPOINT ["node", "build/index.js"]
